# Generated by Django 4.1.7 on 2023-04-01 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_slug_unit_recipe_servings_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_time_unit',
            new_name='servings_preparation_time_unit',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
    ]
