# Generated by Django 4.1.7 on 2023-04-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_servings_preparation_time_unit_recipe_preparation_time_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_publised',
            new_name='is_published',
        ),
    ]
