# Generated by Django 4.1.7 on 2023-06-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_options_alter_recipe_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
