# Generated by Django 4.1.7 on 2023-06-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeManager',
        ),
    ]
